import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css"
import localFont from "next/font/local";
import { Questrial } from "next/font/google";
import Header from "@/app/navbar/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

// BODY FONT / New Farm - family
export const bodyFont = localFont({
  src: [
    { path: "../public/fonts/fonnts.com-New_Farm_Thin.otf", weight: "100" },
    { path: "../public/fonts/fonnts.com-New_Farm_Light.otf", weight: "300" },
    { path: "../public/fonts/fonnts.com-New_Farm_Regular.otf", weight: "400" },
    { path: "../public/fonts/fonnts.com-New_Farm_Medium.otf", weight: "500" },
    { path: "../public/fonts/fonnts.com-New_Farm_Bold.otf", weight: "700" },
  ],
  variable: "--font-body",
});

// TITLE FONT / (Fat Frank)
export const titleFont = localFont({
  src: "../public/fonts/fonnts.com-FatFrank_Heavy.otf",
  variable: "--font-title",
});

// NAVBAR / QUESTRIAL (Google font)
export const navbarFont = Questrial({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-navbar",
});

/*

┌─────────────────────────────────────────────────────┐
│ 1. Sources loaded in Next.js                        │
│   - bodyFont → New Farm family                      │
│   - titleFont → FatFrank                            │
│   - navbarFont → Questrial (Google fonts)           │
│                                                     │
└─────────────────────────────────────────────────────┘

*/

/*
    ======== ENTRY POINT: RootLayout component ========
    - Wraps the entire application
    - Applies global styles and fonts
    - Renders the Header component and children content
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} 
                  ${geistMono.variable} 
                  ${bodyFont.variable} 
                  ${titleFont.variable} 
                  ${navbarFont.variable} 
                  antialiased w-full 
                   overflow-x-hidden`}
      
      >
        <Header />
       {/* centered content */}
        <div className=" mx-auto w-full">
          
        {children}

        </div>
      </body>
    </html>
  );
}
